name = "FigureHelpers"
uuid = "9ae22f58-2487-4805-bfc5-386577db46c8"
authors = ["Thomas Wutzler <bgctw@arcor.de>"]
version = "0.1.0"

[deps]
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"

[extensions]
FigureHelpersAoGExt = ["CairoMakie", "AlgebraOfGraphics"]
FigureHelpersCairoMakieExt = ["CairoMakie", "KernelDensity"]
FigureHelpersMCMCChainsExt = "MCMCChains"

[compat]
AlgebraOfGraphics = "0.9.4, 0.10"
CairoMakie = "0.13.2"
KernelDensity = "0.6.10"
MCMCChains = "6.0.7"
Parameters = "0.12.3"
StatsBase = "0.34.5"
julia = "1.10"

[workspace]
projects = ["test", "docs"]
