name = "TwPrototypes"
uuid = "9ae22f58-2487-4805-bfc5-386577db46c7"
authors = ["Thomas Wutzler <bgctw@arcor.de>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"

[compat]
julia = "1.5"
